version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing global dependencies and setting up environment"
      - npm i -g aws-cdk
      - npm i -g playwright
      - playwright install --with-deps
  pre_build:
    commands:
      - echo "Installing microservices and frontend dependencies"
      - cd $CODEBUILD_SRC_DIR/frontend && npm i
      - cd $CODEBUILD_SRC_DIR/infra && npm i
      - cd $CODEBUILD_SRC_DIR/backend && npm i
      - echo "-- PHASE 1 Static code analysis --"
      - cd $CODEBUILD_SRC_DIR/frontend && npm run lint
      - cd $CODEBUILD_SRC_DIR/backend && npm run lint
  build:
    commands:
      - echo "--- PHASE 2 Unit Testing & Coverage ---"
      - cd $CODEBUILD_SRC_DIR/frontend && npm run test
      - cd $CODEBUILD_SRC_DIR/backend && npm run test
      - echo "Compiling application binaries and production bundles..."
      - cd $CODEBUILD_SRC_DIR/frontend && npm run build -- --configuration=production
      - cd $CODEBUILD_SRC_DIR/backend && npm run build
  post_build:
    commands:
      - echo "--- PHASE 3 Infrastructure Deployment via AWS CDK ---"
      - cd $CODEBUILD_SRC_DIR/infra && npx cdk synth
      - cd $CODEBUILD_SRC_DIR/infra && npx cdk deploy --all --require-approval never
      - echo "--- PHASE 4 Integration & End-to-End (E2E) QA (later) ---"
reports:
  3pl-unit-test-reports:
    files:
      - 'backend/coverage/junit.xml'
      - 'frontend/js-reports/junit.xml'
    file-format: 'JUNITXML'
  3pl-coverage-reports:
    files:
      - 'backend/coverage/clover.xml'
      - 'frontend/coverage/clover.xml'
    file-format: 'CLOVERXML'
artifacts:
  files:
    - 'frontend/dist/**/*'
    - 'backend/dist/**/*'